### ISSUE TITLE
Freemarker snippets cause error

### ISSUE THREAD

**Issue by caneta** [honza/vim-snippets#1076]
Hi everyone.
With brand new [freemarker snippets](https://github.com/honza/vim-snippets/pull/1075) merged to master few days ago, I get the following error:
```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/candini/.config/nvim/plugins/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/home/candini/.config/nvim/plugins/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 848, in _track_change
    self._try_expand(autotrigger_only=True)
  File "/home/candini/.config/nvim/plugins/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 694, in _try_expand
    snippets = self._snips(before, False, autotrigger_only)
  File "/home/candini/.config/nvim/plugins/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 574, in _snips
    source.ensure(filetypes)
  File "/home/candini/.config/nvim/plugins/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 32, in ensure
    self._load_snippets_for(ft)
  File "/home/candini/.config/nvim/plugins/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 54, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/home/candini/.config/nvim/plugins/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 69, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file._base.SnippetSyntaxError: Invalid line '<#assign ${1} = ${0:${VISUAL}} />' in .config/nvim/plugins/vim-snippets/snippets/freemarker.snippets:4
```
Steps to reproduce:
1. open  an .ftl file with vim (or nvim, in my case): `nvim test.ftl`
2. try to insert the "if" snippets

Before merge, with my custom freemarker.snippets file, I never experienced this parsing problem.
Any ideas?

**Comment by lpil** [comment]
The snipmate snippets have been added in the incorrect format. I'll fix this.

**Comment by caneta** [comment]
Now it works, thanks!
