### ISSUE TITLE
Error in stylus.snippets

### ISSUE THREAD

**Issue by pgilad** [honza/vim-snippets#499]
Seems like stylus `!important` line is causing some bad behavior:

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/pgilad/vimfiles/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 54, in wrapper
    return func(self, *args, **kwds)
  File "/Users/pgilad/vimfiles/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 149, in snippets_in_current_scope
    snippets = self._snips(before, True)
  File "/Users/pgilad/vimfiles/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 467, in _snips
    source.ensure(filetypes)
  File "/Users/pgilad/vimfiles/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 37, in ensure
    self._load_snippets_for(ft)
  File "/Users/pgilad/vimfiles/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 67, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/Users/pgilad/vimfiles/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 83, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
SnippetSyntaxError: Invalid line '    !important' in ~/vimfiles/bundle/vim-snippets/snippets/stylus.snippets:2
```

**Comment by SirVer** [comment]
This line starts with spaces which is illegal for snipmate snippets. it needs to be changed to start with tabs.

**Comment by pgilad** [comment]
So that would be for the entire file? I'll submit a PR
