### ISSUE TITLE
C# snippet completion throws syntax errors

### ISSUE THREAD

**Issue by Chiel92** [honza/vim-snippets#585]
When I open an empty C# file, type some characters and trigger the snippet completion (Ctrl-J in my case), I get the following error message:

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/chiel/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 56, in wrapper
    return func(self, *args, **kwds)
  File "/home/chiel/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 146, in expand_or_jump
    rv = self._try_expand()
  File "/home/chiel/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 577, in _try_expand
    snippets = self._snips(before, False)
  File "/home/chiel/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 492, in _snips
    source.ensure(filetypes)
  File "/home/chiel/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 43, in ensure
    self._load_snippets_for(ft)
  File "/home/chiel/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 74, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/home/chiel/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 93, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
SnippetSyntaxError: Invalid line '    ${1:public }static void Main(string[] args) {' in .vim/bundle/vim-snippets/snippets/cs.snippets:73
```

**Comment by lpil** [comment]
Looks like someone broke these snippets and then someone merged it in. :(

I'll fix these.

**Comment by lpil** [comment]
There we go. Thanks for the report!
