### ISSUE TITLE
Crash with Javascript bemjson snippets

### ISSUE THREAD

**Issue by jorgesumle** [honza/vim-snippets#790]
I write the a letter in insert mode and I get an error. 

An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/jorge/.vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/home/jorge/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 843, in _track_change
    self._try_expand(autotrigger_only=True)
  File "/home/jorge/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 702, in _try_expand
    snippets = self._snips(before, False, autotrigger_only)
  File "/home/jorge/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 575, in _snips
    source.ensure(filetypes, cached=autotrigger_only)
  File "/home/jorge/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 47, in ensure
    self._load_snippets_for(ft)
  File "/home/jorge/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 80, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/home/jorge/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 99, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file._base.SnippetSyntaxError: Invalid line 'mi - BEM mix mod' in javascript/bemjson.snippets:45

Removed the lines from that snippet from bemjson.snippets and the problem was fixed. Just wanted to notify that problem. I don't even know what is bemjson.

**Comment by soyuka** [comment]
#792
