### ISSUE TITLE
Invalid version breaks UltiSnips

### ISSUE THREAD

**Issue by carlitux** [honza/vim-snippets#933]
```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/carlitux/.cache/dein/repos/github.com/SirVer/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/Users/carlitux/.cache/dein/repos/github.com/SirVer/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 856, in _track_change
    self._try_expand(autotrigger_only=True)
  File "/Users/carlitux/.cache/dein/repos/github.com/SirVer/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 702, in _try_expand
    snippets = self._snips(before, False, autotrigger_only)
  File "/Users/carlitux/.cache/dein/repos/github.com/SirVer/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 575, in _snips
    source.ensure(filetypes, cached=autotrigger_only)
  File "/Users/carlitux/.cache/dein/repos/github.com/SirVer/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 47, in ensure
    self._load_snippets_for(ft)
  File "/Users/carlitux/.cache/dein/repos/github.com/SirVer/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 80, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/Users/carlitux/.cache/dein/repos/github.com/SirVer/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 99, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file._base.SnippetSyntaxError: Invalid line 'version 1' in ~/.cache/dein/repos/github.com/honza/vim-snippets/snippets/javascript/javascript-jasmine.snippets:1
```

**Comment by ivanalejandro0** [comment]
Same here, I think this problem appeared right after https://github.com/honza/vim-snippets/pull/931 and https://github.com/honza/vim-snippets/pull/932

**Comment by vimsucks** [comment]
Commenting out "version 1", the first line of the file `javascript-jasmine.snippets` would fix it.

**Comment by lpil** [comment]
Thanks all!
