### ISSUE TITLE
Error on javascript.jsx filetype

### ISSUE THREAD

**Issue by aliev** [honza/vim-snippets#937]
After updating UltiSnips and vim-snippets I've an error:

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/apple/.vim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/Users/apple/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 856, in _track_change
    self._try_expand(autotrigger_only=True)
  File "/Users/apple/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 702, in _try_expand
    snippets = self._snips(before, False, autotrigger_only)
  File "/Users/apple/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 575, in _snips
    source.ensure(filetypes, cached=autotrigger_only)
  File "/Users/apple/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 47, in ensure
    self._load_snippets_for(ft)
  File "/Users/apple/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 80, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/Users/apple/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 99, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
SnippetSyntaxError: Invalid line 'version 1' in ~/.vim/plugged/vim-snippets/snippets/javascript/javascript-jasmine.snippets:1
```

on javascript.jsx filetype

**Comment by letientai299** [comment]
This issue should be fixed already with recent commit (459449bb9987a0f88c5ab3c099cc12fd69298281). Please update your plugin.
